name: Generate and Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.3' 

      - name: Run Go program
        run: go run main.go

      - name: Upload email.txt as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-email-artifact
          path: email.txt